In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

[]


In [2]:
s=tf.InteractiveSession()

In [3]:
a=tf.constant(list(np.arange(0,10)))

In [4]:
t=tf.slice(a,[1],[4])

In [5]:
t.eval()

array([1, 2, 3, 4], dtype=int32)

In [6]:
a.eval()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [7]:
a1=tf.constant(np.array(range(15)).reshape((3,5)))

In [8]:
a1.eval()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
t=tf.slice(a1,[1,0],[2,3])

In [10]:
t.eval()

array([[ 5,  6,  7],
       [10, 11, 12]])

In [11]:
t=tf.slice(a1,[1,0],[1,3])

In [12]:
t.eval()

array([[5, 6, 7]])

In [13]:
#Strided Slice

In [14]:
a1=tf.constant(np.array(range(25)).reshape((5,5)))

In [15]:
t=tf.strided_slice(a1,[0,0],[4,4],[2,2])

In [16]:
t.eval()  #so last element is not included     [0.0] is corrdinate of first element and [4,4] is last element coordinate

array([[ 0,  2],
       [10, 12]])

In [17]:
a1.eval()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
t=tf.strided_slice(a1,[0,0],[4,4],[1,2])

In [19]:
t.eval()

array([[ 0,  2],
       [ 5,  7],
       [10, 12],
       [15, 17]])